version: "3.8"

services:
  backend:
    build:
      context: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    depends_on:
      - mysql

  mysql:
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: gocar
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
